version: 2.1

executors:
  default:
    docker:
      - image: circleci/php:7.4-cli

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run:
          name: PHP Version
          command: php --version
      - run:
          name: Composer version
          command: composer --version
      - run:
          name: Composer validate
          command: composer validate
      - run:
          name: Composer install
          command: composer install --no-interaction
      - run:
          name: PHP CodeSniffer
          command: mkdir -p test-results/phpcs && composer run test:ci:phpcs
          when: always
      - run:
          name: PHPStan
          command: mkdir -p test-results/phpstan && composer run test:ci:phpstan
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test
